import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Basir",
      email: "admin@basir.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Janet",
      email: "janet@dago.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
    {
      name: "Alon",
      email: "alon@dago.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Jessy's Veil",
      category: "accessory",
      image: "/media/brides-img/accessory1.jpeg",
      countInStock: 10,
      salePrice: 200,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Mary's Veil",
      category: "accessory",
      image: "/media/brides-img/accessory2.jpg",
      countInStock: 10,
      salePrice: 200,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Pedro's Veil",
      category: "accessory",
      image: "/media/brides-img/accessory3.jpeg",
      countInStock: 10,
      salePrice: 150,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Carol's Veil",
      category: "accessory",
      image: "/media/brides-img/accessory12.jpg",
      countInStock: 10,
      salePrice: 180,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Mareta's Veil",
      category: "accessory",
      image: "/media/brides-img/accessory6.jpg",
      countInStock: 10,
      salePrice: 300,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Coco's Veil",
      category: "accessory",
      image: "/media/brides-img/accessory7.jpg",
      countInStock: 10,
      salePrice: 430,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Wendy's Veil",
      category: "accessory",
      image: "/media/brides-img/accessory8.jpg",
      countInStock: 10,
      salePrice: 400,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Awa's Veil",
      category: "accessory",
      image: "/media/brides-img/accessory9.jpg",
      countInStock: 10,
      salePrice: 360,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Huanes's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory10.jpg",
      countInStock: 10,
      salePrice: 250,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Lauren's Veil",
      category: "accessory",
      image: "/media/brides-img/accessory11.jpeg",
      countInStock: 10,
      salePrice: 250,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },

    {
      name: "Emmy London Victoria Dress",
      category: "dresses",
      image: "/media/brides-img/dress1.jpg",
      countInStock: 10,
      salePrice: 5000,
      price: 8000,
      rating: 3.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Markarian",
      category: "dresses",
      image: "/media/brides-img/dress2.jpg",
      countInStock: 10,
      salePrice: 3200,
      price: 5000,
      rating: 3.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Galia Lahav",
      category: "desses",
      image: "/media/brides-img/dress3.jpg",
      countInStock: 10,
      salePrice: 3200,
      price: 4500,
      rating: 1.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Monique Lhuillier",
      category: "dresses",
      image: "/media/brides-img/dress4.jpg",
      countInStock: 10,
      salePrice: 2200,
      price: 2500,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Diana Gown",
      category: "dresses",
      image: "/media/brides-img/dress5.jpg",
      countInStock: 10,
      salePrice: 5200,
      price: 6500,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "David's Brida",
      category: "dresses",
      image: "/media/brides-img/dress6.jpg",
      countInStock: 10,
      salePrice: 8200,
      price: 9500,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Ian Stuart Dresses",
      category: "accesory",
      image: "/media/brides-img/dress7.jpg",
      countInStock: 10,
      salePrice: 6200,
      price: 7500,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Candy's Dresses",
      category: "accesory",
      image: "/media/brides-img/dress8.jpg",
      countInStock: 10,
      salePrice: 6200,
      price: 7500,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Jo Barnes Dresses",
      category: "dress",
      image: "/media/brides-img/dress9.jpg",
      countInStock: 10,
      salePrice: 3200,
      price: 4500,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Coussini Dresses",
      category: "dress",
      image: "/media/brides-img/dress10.jpg",
      countInStock: 10,
      salePrice: 6200,
      price: 7500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },

    {
      name: "Honey Sandal",
      category: "shoe",
      image: "/media/brides-img/shoe1.jpg",
      countInStock: 10,
      salePrice: 620,
      price: 750.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Diana's Sandal",
      category: "shoe",
      image: "/media/brides-img/shoe2.jpeg",
      countInStock: 10,
      salePrice: 620,
      price: 700.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Lune Heel",
      category: "shoe",
      image: "/media/brides-img/shoe3.jpg",
      countInStock: 10,
      salePrice: 600,
      price: 900.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Paily Sandal",
      category: "shoe",
      image: "/media/brides-img/shoe4.jpg",
      countInStock: 10,
      salePrice: 950,
      price: 1500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Sana Heels",
      category: "shoe",
      image: "/media/brides-img/shoe11.jpeg",
      countInStock: 10,
      salePrice: 420,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Melany's Heels",
      category: "shoe",
      image: "/media/brides-img/shoe6.jpg",
      countInStock: 10,
      salePrice: 720,
      price: 850.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Miel Heels",
      category: "shoe",
      image: "/media/brides-img/shoe7.jpg",
      countInStock: 10,
      salePrice: 620,
      price: 750.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Isabel's Sandals",
      category: "shoe",
      image: "/media/brides-img/shoe8.jpg",
      countInStock: 10,
      salePrice: 520,
      price: 600.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Bottega's Heels",
      category: "shoe",
      image: "/media/brides-img/shoe9.jpg",
      countInStock: 10,
      salePrice: 620,
      price: 900.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      name: "Danish's Sandals",
      category: "shoe",
      image: "/media/brides-img/shoe10.jpg",
      countInStock: 10,
      salePrice: 680,
      price: 700.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
  ],
};
export default data;
