const data = {
  products: [
    {
      _id: "1",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory1.jpeg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "2",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory2.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "3",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory3.jpeg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "4",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory12.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "6",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory6.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "7",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory7.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "8",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory8.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "9",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory9.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "10",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory10.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "11",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/accessory11.jpeg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },

    {
      _id: "12",
      name: "Emmy London Victoria Heels",
      category: "dresses",
      image: "/media/brides-img/dress1.jpg",
      countInStock: 10,
      salePrice: 5000,
      price: 8000,
      rating: 3.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "13",
      name: "Markarian",
      category: "dresses",
      image: "/media/brides-img/dress2.jpg",
      countInStock: 10,
      price: 5000,
      rating: 3.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "14",
      name: "Galia Lahav",
      category: "desses",
      image: "/media/brides-img/dress3.jpg",
      countInStock: 10,
      price: 4500,
      rating: 1.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "15",
      name: "Monique Lhuillier",
      category: "dresses",
      image: "/media/brides-img/dress4.jpg",
      countInStock: 10,
      price: 25000,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "16",
      name: "Bhldn",
      category: "dresses",
      image: "/media/brides-img/dress5.jpg",
      countInStock: 10,
      price: 65000,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "17",
      name: "David's Brida",
      category: "dresses",
      image: "/media/brides-img/dress6.jpg",
      countInStock: 10,
      price: 95000,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "18",
      name: "Ian Stuart Gloves",
      category: "accesory",
      image: "/media/brides-img/dress7.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "19",
      name: "Dessy's Veil",
      category: "accesory",
      image: "/media/brides-img/dress8.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "20",
      name: "Jo Barnes Accesories",
      category: "dress",
      image: "/media/brides-img/dress9.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "21",
      name: "Jo Barnes Accesories",
      category: "dress",
      image: "/media/brides-img/dress10.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },

    {
      _id: "22",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/shoe1.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "23",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/shoe2.jpeg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "24",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/shoe3.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "25",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/shoe4.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "26",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/shoe11.jpeg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "27",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/shoe6.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "28",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/shoe7.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "29",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/shoe8.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "30",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/shoe9.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
    {
      _id: "31",
      name: "Dessy's Veil",
      category: "shoe",
      image: "/media/brides-img/shoe10.jpg",
      countInStock: 10,
      price: 500.0,
      rating: 4.5,
      numReviews: 10,
      description:
        "The precise color of the items may vary depending on the specific monitor, the settings and the lighting conditions. The items colors depicted should only be used as an approximate guide.",
    },
  ],
};
export default data;
